"""agregar campo stock a productos

Revision ID: 34cffdd1bea8
Revises: eb157ee531ec
Create Date: 2025-10-07 20:50:17.792655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cffdd1bea8'
down_revision: Union[str, Sequence[str], None] = 'eb157ee531ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'stock')
    # ### end Alembic commands ###
